"""create packages table

Revision ID: 00d7825e9d8f
Revises: 43a90a8f0252
Create Date: 2021-11-08 08:10:14.502308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d7825e9d8f'
down_revision = '43a90a8f0252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('albums_reviewId_fkey', 'albums', type_='foreignkey')
    op.drop_column('albums', 'reviewId')
    op.add_column('reviews', sa.Column('albumId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'albums', ['albumId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'albumId')
    op.add_column('albums', sa.Column('reviewId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('albums_reviewId_fkey', 'albums', 'reviews', ['reviewId'], ['id'])
    # ### end Alembic commands ###
