"""create packages table

Revision ID: 9e843514263c
Revises: cf455481910f
Create Date: 2021-11-08 14:40:08.294123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e843514263c'
down_revision = 'cf455481910f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('albums', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
