"""create packages table

Revision ID: cf455481910f
Revises: 9a4bbd69c375
Create Date: 2021-11-08 11:09:09.379306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf455481910f'
down_revision = '9a4bbd69c375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'year')
    # ### end Alembic commands ###
