"""create packages table

Revision ID: dbf4c14af56d
Revises: 4a3a806caefe
Create Date: 2021-11-09 06:24:53.824851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf4c14af56d'
down_revision = '4a3a806caefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs_playlists',
    sa.Column('songId', sa.Integer(), nullable=True),
    sa.Column('playlistId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlistId'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['songId'], ['songs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_playlists')
    # ### end Alembic commands ###
