"""create packages table

Revision ID: ef2f8ba3efd1
Revises: dbf4c14af56d
Create Date: 2021-11-09 06:53:15.659314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2f8ba3efd1'
down_revision = 'dbf4c14af56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs_playlists', 'songId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('songs_playlists', 'playlistId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs_playlists', 'playlistId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs_playlists', 'songId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
